<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.6" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hook2Stream.AppHost</RootNamespace>
    <UserSecretsId>hook2stream-apphost-local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Hook2Stream.Api/Hook2Stream.Api.csproj" />
    <ProjectReference Include="../Hook2Stream.Application/Hook2Stream.Application.csproj"
                      IsAspireProjectResource="false" />
    <ProjectReference Include="../Hook2Stream.Bootstrapper/Hook2Stream.Bootstrapper.csproj" />
    <ProjectReference Include="../Hook2Stream.Worker/Hook2Stream.Worker.csproj" />
  </ItemGroup>

</Project>
