// <auto-generated />
using System;
using Hook2Stream.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hook2Stream.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Hook2StreamDbContext))]
    [Migration("20260720120040_ArtworkConsentAndBackgrounds")]
    partial class ArtworkConsentAndBackgrounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hook2Stream.Domain.ApiIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SecondaryResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_resource_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_api_idempotency_records");

                    b.HasIndex("WorkspaceId", "Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_api_idempotency_records_workspace_id_scope_key");

                    b.ToTable("api_idempotency_records", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("clerk_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ClerkSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_clerk_subject");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.ArtworkPackRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBySubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("approved_by_subject");

                    b.Property<string>("BackgroundAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb")
                        .HasColumnName("background_asset_ids_json");

                    b.Property<string>("CandidateAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("candidate_asset_ids_json");

                    b.Property<string>("CompositionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("composition_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("OperationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("operation_number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt");

                    b.Property<Guid?>("SelectedAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_asset_id");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_artwork_pack_revisions");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_artwork_pack_revisions_project_id_number");

                    b.HasIndex("ProjectId", "OperationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_artwork_pack_revisions_project_id_operation_number");

                    b.ToTable("artwork_pack_revisions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_workspace_id_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.BrandKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color");

                    b.Property<string>("BodyFont")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("body_font");

                    b.Property<bool>("CharacterLayerEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("character_layer_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCta")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("default_cta");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("HeadingFont")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("heading_font");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("secondary_color");

                    b.Property<string>("SmartLink")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("smart_link");

                    b.Property<string>("ToneRestrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tone_restrictions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_brand_kits");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_kits_workspace_id");

                    b.ToTable("brand_kits", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.CampaignPlanRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtworkPackRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("artwork_pack_revision_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("HookSetRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hook_set_revision_id");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items_json");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TranscriptRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transcript_revision_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_plan_revisions");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_plan_revisions_project_id_number");

                    b.ToTable("campaign_plan_revisions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.HookSetRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HooksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hooks_json");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TranscriptRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transcript_revision_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_hook_set_revisions");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_hook_set_revisions_project_id_number");

                    b.ToTable("hook_set_revisions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("Source", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_source_message_id");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("HandlerVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("v1")
                        .HasColumnName("handler_version");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InputFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_fingerprint");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PayloadSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("payload_schema_version");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.Property<string>("PipelineStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline_stage");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<string>("ProgressStage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("progress_stage");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RequiredCapability")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("media")
                        .HasColumnName("required_capability");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_jobs_project_id");

                    b.HasIndex("State", "AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_jobs_state_available_at_created_at");

                    b.HasIndex("WorkspaceId", "ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_jobs_workspace_id_project_id_created_at");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.JobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_job_attempts");

                    b.HasIndex("JobId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_job_attempts_job_id_number");

                    b.ToTable("job_attempts", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.JobEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_job_events");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_job_events_sequence");

                    b.HasIndex("JobId", "Sequence")
                        .HasDatabaseName("ix_job_events_job_id_sequence");

                    b.ToTable("job_events", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ActualBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_bytes");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("audio_codec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeclaredBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("declared_bytes");

                    b.Property<string>("DeclaredContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("declared_content_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detected_content_type");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_message");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<int>("Origin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("origin");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProvenanceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance_json");

                    b.Property<int>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("purpose");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid?>("SupersedesAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_asset_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("video_codec");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_media_assets_object_key");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_media_assets_project_id");

                    b.HasIndex("WorkspaceId", "ProjectId", "Kind", "IsActive")
                        .HasDatabaseName("ix_media_assets_workspace_id_project_id_kind_is_active");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.MediaDerivative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_milliseconds");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("ProcessorVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("processor_version");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_derivatives");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_media_derivatives_object_key");

                    b.HasIndex("AssetId", "Kind", "ProcessorVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_media_derivatives_asset_id_kind_processor_version");

                    b.ToTable("media_derivatives", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dedupe_key");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("destination");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_dedupe_key");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InputFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_fingerprint");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_runs");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_runs_project_id_number");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockerCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("blocker_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_job_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_stages");

                    b.HasIndex("PipelineRunId", "Lane")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_stages_pipeline_run_id_lane");

                    b.ToTable("pipeline_stages", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.ProjectEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_project_events");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_project_events_sequence");

                    b.HasIndex("WorkspaceId", "ProjectId", "Sequence")
                        .HasDatabaseName("ix_project_events_workspace_id_project_id_sequence");

                    b.ToTable("project_events", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.ReleaseProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("artist_name");

                    b.Property<long>("BrandKitVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_kit_version");

                    b.Property<DateOnly?>("CampaignStartDate")
                        .HasColumnType("date")
                        .HasColumnName("campaign_start_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentArtworkPackRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_artwork_pack_revision_id");

                    b.Property<Guid?>("CurrentCampaignPlanRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_campaign_plan_revision_id");

                    b.Property<Guid?>("CurrentHookSetRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_hook_set_revision_id");

                    b.Property<Guid?>("CurrentTranscriptRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_transcript_revision_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FlowKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("flow_kind");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsInstrumental")
                        .HasColumnType("boolean")
                        .HasColumnName("is_instrumental");

                    b.Property<bool>("IsInstrumentalConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_instrumental_confirmed");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("LyricsText")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("lyrics_text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("ProjectLabel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("project_label");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<DateTimeOffset?>("SetupCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("setup_completed_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("TrackTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("track_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_release_projects");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_release_projects_workspace_id_created_at");

                    b.ToTable("release_projects", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.RightsAttestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_subject");

                    b.Property<bool>("AllowsExternalAiArtwork")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_external_ai_artwork");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("OwnsAudioRights")
                        .HasColumnType("boolean")
                        .HasColumnName("owns_audio_rights");

                    b.Property<bool>("OwnsLyricsRights")
                        .HasColumnType("boolean")
                        .HasColumnName("owns_lyrics_rights");

                    b.Property<bool>("OwnsVisualRights")
                        .HasColumnType("boolean")
                        .HasColumnName("owns_visual_rights");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SyntheticContentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("synthetic_content_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rights_attestations");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_rights_attestations_project_id");

                    b.ToTable("rights_attestations", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.TrackAnalysisRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("ProcessorVersionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("processor_versions_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_asset_id");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_track_analysis_revisions");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_track_analysis_revisions_project_id_number");

                    b.ToTable("track_analysis_revisions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.TranscriptRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBySubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("approved_by_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PhrasesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("phrases_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid?>("SupersedesRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_revision_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_transcript_revisions");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_transcript_revisions_project_id_number");

                    b.ToTable("transcript_revisions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.UploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AbortedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aborted_at");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsMultipart")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multipart");

                    b.Property<string>("MultipartUploadId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("multipart_upload_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<long>("PartSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("part_size_bytes");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_sessions");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_upload_sessions_asset_id");

                    b.HasIndex("WorkspaceId", "ProjectId", "State")
                        .HasDatabaseName("ix_upload_sessions_workspace_id_project_id_state");

                    b.ToTable("upload_sessions", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("PrivacyAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("privacy_accepted_at");

                    b.Property<string>("PrivacyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("privacy_version");

                    b.Property<DateTimeOffset>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_owner_user_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Hook2Stream.Domain.BrandKit", b =>
                {
                    b.HasOne("Hook2Stream.Domain.Workspace", "Workspace")
                        .WithOne("BrandKit")
                        .HasForeignKey("Hook2Stream.Domain.BrandKit", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_kits_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Hook2Stream.Domain.Job", b =>
                {
                    b.HasOne("Hook2Stream.Domain.ReleaseProject", "Project")
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_jobs_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hook2Stream.Domain.JobAttempt", b =>
                {
                    b.HasOne("Hook2Stream.Domain.Job", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_attempts_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hook2Stream.Domain.JobEvent", b =>
                {
                    b.HasOne("Hook2Stream.Domain.Job", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_events_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hook2Stream.Domain.MediaAsset", b =>
                {
                    b.HasOne("Hook2Stream.Domain.ReleaseProject", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_assets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hook2Stream.Domain.MediaDerivative", b =>
                {
                    b.HasOne("Hook2Stream.Domain.MediaAsset", "Asset")
                        .WithMany("Derivatives")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_derivatives_media_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Hook2Stream.Domain.PipelineRun", b =>
                {
                    b.HasOne("Hook2Stream.Domain.ReleaseProject", "Project")
                        .WithMany("PipelineRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_runs_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hook2Stream.Domain.PipelineStage", b =>
                {
                    b.HasOne("Hook2Stream.Domain.PipelineRun", "PipelineRun")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pipeline_stages_pipeline_runs_pipeline_run_id");

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("Hook2Stream.Domain.ReleaseProject", b =>
                {
                    b.HasOne("Hook2Stream.Domain.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_projects_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Hook2Stream.Domain.RightsAttestation", b =>
                {
                    b.HasOne("Hook2Stream.Domain.ReleaseProject", "Project")
                        .WithOne("RightsAttestation")
                        .HasForeignKey("Hook2Stream.Domain.RightsAttestation", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rights_attestations_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hook2Stream.Domain.UploadSession", b =>
                {
                    b.HasOne("Hook2Stream.Domain.MediaAsset", "Asset")
                        .WithMany("UploadSessions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_upload_sessions_media_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Hook2Stream.Domain.Workspace", b =>
                {
                    b.HasOne("Hook2Stream.Domain.AppUser", "OwnerUser")
                        .WithOne("Workspace")
                        .HasForeignKey("Hook2Stream.Domain.Workspace", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_user_id");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Hook2Stream.Domain.AppUser", b =>
                {
                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Hook2Stream.Domain.Job", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Hook2Stream.Domain.MediaAsset", b =>
                {
                    b.Navigation("Derivatives");

                    b.Navigation("UploadSessions");
                });

            modelBuilder.Entity("Hook2Stream.Domain.PipelineRun", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Hook2Stream.Domain.ReleaseProject", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Jobs");

                    b.Navigation("PipelineRuns");

                    b.Navigation("RightsAttestation");
                });

            modelBuilder.Entity("Hook2Stream.Domain.Workspace", b =>
                {
                    b.Navigation("BrandKit");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
