/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand-kit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandKitResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBrandKitRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrandKitResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeArchived?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReleaseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateReleaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletionStatusResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/rights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RightsAttestationResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RightsAttestationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RightsAttestationResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUploadRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/assets/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderAssetsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetResponse"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetDeletionResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/audio-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuickAudioUploadRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuickAudioUploadResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupReleaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleaseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranscriptResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PutTranscriptRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranscriptResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/transcript/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveRevisionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranscriptResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/transcript/regenerations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtworkPackResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateArtworkRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/artwork/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateArtworkSelectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtworkPackResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/artwork/cover-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveRevisionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtworkPackResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/hooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HookSetResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PutHooksRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HookSetResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/campaign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/campaign/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PutCampaignItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/preview/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RetryPreviewRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAcceptedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/assets/{assetId}/view-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetReadUrlResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCheckoutRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartRenderRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenderBatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/renders/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    batchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenderBatchStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/artwork/clean-cover/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DownloadGrantResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/assets/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{projectId}/downloads/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadSessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{sessionId}/parts/{partNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                    partNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadPartResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteUploadRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteUploadResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{sessionId}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountResponse: {
            /** Format: uuid */
            userId: string;
            subject: string;
            email: null | string;
            displayName: null | string;
            onboardingRequired: boolean;
            /** Format: uuid */
            workspaceId: null | string;
            workspaceName: null | string;
            /** Format: int64 */
            version: null | number | string;
        };
        ApproveRevisionRequest: {
            /** Format: uuid */
            revisionId: string;
        };
        ArtworkPackResponse: {
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            number: number | string;
            /** Format: int32 */
            operationNumber: number | string;
            state: components["schemas"]["RevisionState"];
            prompt: string;
            candidateAssetIds: string[];
            backgroundAssetIds: string[];
            /** Format: uuid */
            selectedAssetId: null | string;
            compositionJson: string;
            /** Format: date-time */
            approvedAt: null | string;
            /** Format: int64 */
            version: number | string;
        };
        AssetDeletionResponse: {
            /** Format: uuid */
            assetId: string;
            /** Format: uuid */
            cleanupJobId: string;
        };
        /** @enum {unknown} */
        AssetKind: "audio" | "cover" | "visual" | "brandCharacter";
        /** @enum {unknown} */
        AssetOrigin: "uploaded" | "generated";
        /** @enum {unknown} */
        AssetPurpose: "source" | "audioMaster" | "coverCandidate" | "approvedCover" | "campaignBackground" | "campaignVideo" | "previewVideo" | "exportBundle" | "cleanCover";
        AssetReadUrlResponse: {
            /** Format: uuid */
            assetId: string;
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        AssetResponse: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["AssetKind"];
            origin: components["schemas"]["AssetOrigin"];
            purpose: components["schemas"]["AssetPurpose"];
            state: components["schemas"]["AssetState"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            declaredBytes: number | string;
            /** Format: int64 */
            actualBytes: null | number | string;
            /** Format: int32 */
            revision: number | string;
            /** Format: int32 */
            sortOrder: number | string;
            isActive: boolean;
            failureCode: null | string;
            failureMessage: null | string;
            /** Format: int64 */
            durationMilliseconds: null | number | string;
            /** Format: int32 */
            width: null | number | string;
            /** Format: int32 */
            height: null | number | string;
            /** Format: int64 */
            version: number | string;
        };
        /** @enum {unknown} */
        AssetState: "reserved" | "uploading" | "uploaded" | "processing" | "ready" | "rejected" | "deleted";
        AuthSessionResponse: {
            authenticated: boolean;
            subject: null | string;
            email: null | string;
            displayName: null | string;
            /** Format: date-time */
            expiresAt: null | string;
            csrfToken: null | string;
        };
        BillingSummaryResponse: {
            /** Format: int32 */
            workspaceArtworkCredits: number | string;
            activeSubscription: null | string;
            entitlements: components["schemas"]["EntitlementResponse"][];
            checkoutEnabled: boolean;
        };
        BrandKitResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            primaryColor: string;
            secondaryColor: string;
            accentColor: string;
            headingFont: string;
            bodyFont: string;
            defaultCta: string;
            smartLink: null | string;
            toneRestrictions: null | string;
            characterLayerEnabled: boolean;
            /** Format: int64 */
            version: number | string;
        };
        CampaignItemRequest: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            slot: number | string;
            template: string;
            hookId: string;
            /** Format: uuid */
            backgroundAssetId: null | string;
            text: string;
            compositionJson: string;
        };
        CampaignResponse: {
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            number: number | string;
            state: components["schemas"]["RevisionState"];
            items: components["schemas"]["CampaignItemRequest"][];
            /** Format: int64 */
            version: number | string;
        };
        CheckoutResponse: {
            /** Format: uuid */
            checkoutId: string;
            productCode: string;
            status: string;
            checkoutUrl: string;
        };
        CompletedPartRequest: {
            /** Format: int32 */
            partNumber: number | string;
            eTag: string;
        };
        CompleteOnboardingRequest: {
            workspaceName: string;
            acceptTerms: boolean;
            acceptPrivacy: boolean;
            termsVersion: string;
            privacyVersion: string;
            displayName: null | string;
        };
        CompleteUploadRequest: {
            parts?: null | components["schemas"]["CompletedPartRequest"][];
        };
        CompleteUploadResponse: {
            /** Format: uuid */
            assetId: string;
            /** Format: uuid */
            jobId: string;
        };
        CreateCheckoutRequest: {
            productCode: string;
            /** Format: uuid */
            projectId: null | string;
            itemIds: null | string[];
            returnPath: string;
        };
        CreateReleaseRequest: {
            projectLabel: string;
            artistName: string;
            trackTitle: string;
            language: string;
            internalNotes: null | string;
            lyricsText: null | string;
            isInstrumental: boolean;
            mode: components["schemas"]["ReleaseMode"];
            /** Format: date */
            releaseDate: null | string;
            /** Format: date */
            campaignStartDate: null | string;
        };
        CreateUploadRequest: {
            kind: components["schemas"]["AssetKind"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number | string;
            /** Format: uuid */
            replacesAssetId: null | string;
        };
        DeletionStatusResponse: {
            /** Format: uuid */
            deletionId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: date-time */
            deletedAt: string;
            /** Format: date-time */
            purgeDueAt: string;
            state: string;
        };
        DownloadGrantResponse: {
            /** Format: uuid */
            assetId: string;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number | string;
            /** Format: int32 */
            width: null | number | string;
            /** Format: int32 */
            height: null | number | string;
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        EntitlementResponse: {
            /** Format: uuid */
            id: string;
            productCode: string;
            /** Format: uuid */
            projectId: null | string;
            state: string;
            /** Format: int32 */
            includedItemCount: number | string;
            itemIds: string[];
            /** Format: int32 */
            remainingContentRerenders: number | string;
            /** Format: date-time */
            validUntil: null | string;
        };
        /** @enum {unknown} */
        FlowKind: "legacy" | "mp3First";
        GenerateArtworkRequest: {
            prompt: string;
            style: null | string;
        };
        HookRequest: {
            id: string;
            kind: string;
            /** Format: int64 */
            startMilliseconds: number | string;
            /** Format: int64 */
            endMilliseconds: number | string;
            label: null | string;
        };
        HookSetResponse: {
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            number: number | string;
            /** Format: uuid */
            transcriptRevisionId: string;
            hooks: components["schemas"]["HookRequest"][];
            /** Format: int64 */
            version: number | string;
        };
        JobAcceptedResponse: {
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            revisionId: null | string;
        };
        JobResponse: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["JobType"];
            state: components["schemas"]["JobState"];
            /** Format: int32 */
            progressPercent: number | string;
            progressStage: null | string;
            errorCode: null | string;
            errorMessage: null | string;
            /** Format: int32 */
            attemptCount: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int64 */
            version: number | string;
        };
        /** @enum {unknown} */
        JobState: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @enum {unknown} */
        JobType: "mediaIngest" | "assetCleanup" | "audioAnalysis" | "transcription" | "artworkGeneration" | "campaignGeneration" | "previewRender" | "finalRender" | "exportBundle" | "cleanCoverRender";
        /** @enum {unknown} */
        PipelineStageState: "notStarted" | "queued" | "running" | "waitingUser" | "retrying" | "succeeded" | "degraded" | "failed" | "cancelled" | "stale";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /** @enum {unknown} */
        ProjectState: "draft" | "analyzing" | "hookReview" | "campaignReady" | "previewReady" | "rendering" | "ready" | "partiallyReady" | "archived";
        PutCampaignItemRequest: {
            template: string;
            hookId: string;
            /** Format: uuid */
            backgroundAssetId: null | string;
            text: string;
            compositionJson: string;
        };
        PutHooksRequest: {
            hooks: components["schemas"]["HookRequest"][];
        };
        PutTranscriptRequest: {
            source: components["schemas"]["TranscriptSource"];
            language: string;
            isInstrumental: boolean;
            phrases: components["schemas"]["TranscriptPhraseRequest"][];
        };
        QuickAudioUploadRequest: {
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number | string;
            confirmsContentRights: boolean;
            allowsExternalAiProcessing: boolean;
        };
        QuickAudioUploadResponse: {
            project: components["schemas"]["ReleaseResponse"];
            upload: components["schemas"]["UploadSessionResponse"];
            workflow: components["schemas"]["WorkflowResponse"];
        };
        ReadinessResponse: {
            ready: boolean;
            missing: string[];
            /** Format: int32 */
            readyVisuals: number | string;
            hasAudio: boolean;
            hasCover: boolean;
            hasLyricsOrInstrumental: boolean;
            hasRightsAttestation: boolean;
        };
        /** @enum {unknown} */
        ReleaseMode: "upcoming" | "released" | "unscheduled";
        ReleaseResponse: {
            /** Format: uuid */
            id: string;
            flowKind: components["schemas"]["FlowKind"];
            projectLabel: string;
            artistName: string;
            trackTitle: string;
            language: string;
            internalNotes: null | string;
            lyricsText: null | string;
            isInstrumental: boolean;
            isInstrumentalConfirmed: boolean;
            mode: components["schemas"]["ReleaseMode"];
            /** Format: date */
            releaseDate: null | string;
            /** Format: date */
            campaignStartDate: null | string;
            state: components["schemas"]["ProjectState"];
            isArchived: boolean;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
            assets: components["schemas"]["AssetResponse"][];
        };
        RenderBatchResponse: {
            /** Format: uuid */
            batchId: string;
            state: string;
            jobIds: string[];
        };
        RenderBatchStatusResponse: {
            /** Format: uuid */
            batchId: string;
            /** Format: uuid */
            entitlementId: string;
            state: string;
            kind: components["schemas"]["RenderRequestKind"];
            items: components["schemas"]["RenderItemStatusResponse"][];
            export: null | components["schemas"]["DownloadGrantResponse"];
            /** Format: date-time */
            completedAt: null | string;
        };
        RenderItemStatusResponse: {
            /** Format: uuid */
            campaignItemId: string;
            state: string;
            /** Format: uuid */
            jobId: null | string;
            errorCode: null | string;
            download: null | components["schemas"]["DownloadGrantResponse"];
        };
        /**
         * @default initial
         * @enum {unknown}
         */
        RenderRequestKind: "initial" | "contentChange" | "technicalRetry";
        ReorderAssetsRequest: {
            assetIds: string[];
        };
        RetryPreviewRequest: {
            /** Format: uuid */
            failedJobId: string;
        };
        /** @enum {unknown} */
        RevisionState: "draft" | "processing" | "readyForReview" | "approved" | "failed" | "superseded";
        RightsAttestationRequest: {
            ownsAudioRights: boolean;
            ownsLyricsRights: boolean;
            ownsVisualRights: boolean;
            allowsExternalAiArtwork: boolean;
            allowsExternalAiProcessing: boolean;
            syntheticContentStatus: components["schemas"]["SyntheticContentStatus"];
            policyVersion: string;
        };
        RightsAttestationResponse: {
            /** Format: uuid */
            id: string;
            ownsAudioRights: boolean;
            ownsLyricsRights: boolean;
            ownsVisualRights: boolean;
            allowsExternalAiArtwork: boolean;
            allowsExternalAiProcessing: boolean;
            syntheticContentStatus: components["schemas"]["SyntheticContentStatus"];
            policyVersion: string;
            /** Format: date-time */
            acceptedAt: string;
            /** Format: uuid */
            audioAssetId: null | string;
            audioFingerprint: null | string;
            /** Format: int64 */
            projectVersion: number | string;
        };
        SetupReleaseRequest: {
            projectLabel: string;
            artistName: string;
            trackTitle: string;
            language: string;
            mode: components["schemas"]["ReleaseMode"];
            /** Format: date */
            releaseDate: null | string;
            /** Format: date */
            campaignStartDate: null | string;
            isInstrumental: boolean;
            isInstrumentalConfirmed: boolean;
            internalNotes: null | string;
        };
        StartRenderRequest: {
            /** Format: uuid */
            entitlementId: string;
            itemIds: string[];
            kind?: components["schemas"]["RenderRequestKind"];
        };
        /** @enum {unknown} */
        SyntheticContentStatus: "none" | "assisted" | "fullySynthetic" | "unknown";
        TranscriptPhraseRequest: {
            id: string;
            /** Format: int32 */
            order: number | string;
            text: string;
            /** Format: int64 */
            startMilliseconds: number | string;
            /** Format: int64 */
            endMilliseconds: number | string;
            /** Format: double */
            confidence: number | string;
            warningAcknowledged: boolean;
            words: null | components["schemas"]["TranscriptWordResponse"][];
        };
        TranscriptResponse: {
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            number: number | string;
            source: components["schemas"]["TranscriptSource"];
            state: components["schemas"]["RevisionState"];
            language: string;
            isInstrumental: boolean;
            phrases: components["schemas"]["TranscriptPhraseRequest"][];
            /** Format: date-time */
            approvedAt: null | string;
            /** Format: int64 */
            version: number | string;
        };
        /** @enum {unknown} */
        TranscriptSource: "automatic" | "imported" | "manual" | "instrumental";
        TranscriptWordResponse: {
            text: string;
            /** Format: int64 */
            startMilliseconds: number | string;
            /** Format: int64 */
            endMilliseconds: number | string;
            /** Format: double */
            confidence: number | string;
        };
        UpdateArtworkSelectionRequest: {
            /** Format: uuid */
            packRevisionId: string;
            /** Format: uuid */
            selectedAssetId: string;
            compositionJson: string;
        };
        UpdateBrandKitRequest: {
            displayName: string;
            primaryColor: string;
            secondaryColor: string;
            accentColor: string;
            headingFont: string;
            bodyFont: string;
            defaultCta: string;
            smartLink: null | string;
            toneRestrictions: null | string;
            characterLayerEnabled: boolean;
        };
        UpdateReleaseRequest: {
            projectLabel: string;
            artistName: string;
            trackTitle: string;
            language: string;
            internalNotes: null | string;
            lyricsText: null | string;
            isInstrumental: boolean;
            mode: components["schemas"]["ReleaseMode"];
            /** Format: date */
            releaseDate: null | string;
            /** Format: date */
            campaignStartDate: null | string;
        };
        UploadPartReceiptResponse: {
            /** Format: int32 */
            partNumber: number | string;
            /** Format: int64 */
            plaintextLength: number | string;
            sha256: string;
            eTag: string;
        };
        UploadPartResponse: {
            /** Format: int32 */
            partNumber: number | string;
            /** Format: int64 */
            plaintextLength: number | string;
            sha256: string;
            eTag: string;
        };
        UploadSessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            assetId: string;
            multipart: boolean;
            uploadUrl: null | string;
            multipartUploadId: null | string;
            /** Format: int64 */
            partSizeBytes: number | string;
            /** Format: int32 */
            partCount: number | string;
            /** Format: date-time */
            urlExpiresAt: string;
            /** Format: date-time */
            sessionExpiresAt: string;
            completedParts?: null | components["schemas"]["UploadPartReceiptResponse"][];
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        /** @enum {unknown} */
        WorkflowLane: "audio" | "analysis" | "transcript" | "artwork" | "hooks" | "campaign" | "preview" | "finalRender";
        WorkflowLaneResponse: {
            lane: components["schemas"]["WorkflowLane"];
            state: components["schemas"]["PipelineStageState"];
            /** Format: int32 */
            progressPercent: number | string;
            blockerCode: null | string;
            errorCode: null | string;
            /** Format: uuid */
            currentJobId: null | string;
        };
        /** @enum {unknown} */
        WorkflowNextAction: "uploadAudio" | "completeSetup" | "confirmRights" | "reviewTranscript" | "reviewArtwork" | "reviewHooks" | "waitForCampaign" | "waitForPreview" | "purchaseRender" | "startFinalRender" | "waitForFinalRender" | "downloadExport" | "retryFailedRenders" | "retryPreview" | null;
        WorkflowResponse: {
            /** Format: uuid */
            projectId: string;
            flowKind: components["schemas"]["FlowKind"];
            /** Format: int64 */
            projectVersion: number | string;
            /** Format: int64 */
            workflowVersion: number | string;
            blockers: string[];
            nextAction: null | components["schemas"]["WorkflowNextAction"];
            lanes: components["schemas"]["WorkflowLaneResponse"][];
            /** Format: uuid */
            currentRenderBatchId?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
