http_port 3128
acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowed_domains dstdomain .your-objectstorage.com .google.com .googleapis.com .gstatic.com .stripe.com
http_access deny !SSL_ports
http_access deny !CONNECT
http_access allow allowed_domains
http_access deny all
access_log stdio:/dev/stdout
cache deny all
via off
forwarded_for delete
request_header_access Authorization deny all
request_header_access Cookie deny all
