<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hook2Stream.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Hook2Stream.Domain/Hook2Stream.Domain.csproj" />
  </ItemGroup>

</Project>
